apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: namouchi-bazzi-andriamasinoro
  labels:
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: gcr-secret
      containers:
      - name: backend
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-2026:namouchi-bazzi-andriamasinoro
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: DEGRADED_MODE
          value: "true"  # ← ACTIVE LE MODE DÉGRADÉ
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
