apiVersion: v1
kind: Pod
metadata:
  name: kuard-liveness
spec:
  containers:
  - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
