apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: frontend
    soft: nginx
  name: kuard-replicaset
spec:
  replicas: 1                     # Nombre d'instance de la charge de travail à déployer
  selector:
    matchLabels:
      app: frontend
      soft: nginx
  template:                       # template: à partir de là, les attributs qui suivent seront ceux du Pod qui va être créé
    metadata:
      labels:
        app: frontend
        soft: nginx
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
        name: kuard
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
