apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: tahercontainer
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
