apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: namouchi-bazzi-andriamasinoro
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/consumer-2026:namouchi-bazzi-andriamasinoro
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
          limits:
            cpu: "10m"
            memory: "64Mi"
